import { ReactNode, Suspense } from 'react';

import { GeistSans } from 'geist/font/sans';

import HeaderAuth from '@/components/header-auth';
import { ThemeSwitcher } from '@/components/theme-switcher';
import Image from 'next/image';
import Link from 'next/link';
import './globals.css';
import Providers from './providers';

const ano = new Date().getFullYear();

const defaultUrl = process.env.VERCEL_URL
  ? `https://${process.env.VERCEL_URL}`
  : 'http://localhost:3000';

export const metadata = {
  metadataBase: new URL(defaultUrl),
  title: `Luluzinha ${ano}`,
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: ReactNode;
};

const RootLayout = ({ children }: RootLayoutProps) => (
  <html lang="pt-br" className={GeistSans.className} suppressHydrationWarning>
    <body className="bg-background text-foreground">
      <Providers>
        <Suspense fallback={<p>Fetching data...</p>}>
          <main className="">
            <div className="">
              <nav className="flex h-16 w-full justify-center border-b border-b-foreground/10">
                <div className="flex w-full items-center justify-between p-3 px-5 text-sm">
                  <Link href="/" className="flex items-center gap-2">
                    <Image
                      src="/fotos/luluzinha.jpg"
                      alt="luluzinha"
                      width={30}
                      height={30}
                    />
                    <p className="font-pacifico text-4xl font-bold text-primary">
                      Lulus
                    </p>
                  </Link>

                  <HeaderAuth />
                </div>
              </nav>
              <div className="flex flex-col p-2">{children}</div>
              <footer className="mx-auto flex w-full items-center justify-center gap-8 border-t py-16 text-center text-xs">
                <ThemeSwitcher />
              </footer>
            </div>
          </main>
        </Suspense>
      </Providers>
    </body>
  </html>
);

export default RootLayout;
